[package]
name = "slack-tui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tui = "0.19"
crossterm = "0.25"
log = "0.4.17"
log4rs = "1.2.0"
home = "0.5.4"
